### PR TITLE
using lodash.isplainobject as external node_module

### PR DESCRIPTION
**Pull request by anshulsahni**
@tyv 
This replaces the lodash.is-plain-object.js in lib with lodash.isplainobject node_module

### CODE REVIEW

**Comment by tyv** [comment]
@anshulsahni cool! 
can you please remove this test also: 
https://github.com/tyv/pick-react-known-prop/blob/master/test/index.js#L71-L145

**Comment by anshulsahni** [comment]
@tyv sure will update it ASAP

**Comment by anshulsahni** [comment]
@tyv test removal done

**Comment by Tvrqvoise** [comment]
Lodash isPlainObject was removed because it caused the bundle size to be massive (around 10x the current size).  How did you get around that?

**Comment by tyv** [comment]
@Tvrqvoise as far as I know they did some changes
```bash
Yuriyt-mac /Users/yuriyt/temp/node_modules l lodash.isplainobject/index.js
-rw-r--r--  1 yuriyt  361602828   3,6K 13 авг  2016 lodash.isplainobject/index.js
```
and it is not compressed, has a lot of comments.

**Comment by anshulsahni** [comment]
@Tvrqvoise @tyv 

lodash creator has now created separate modules for each method so we can download only what we want

**Comment by tyv** [comment]
published

**Pull request merged**
